
export function getArea() {
    return [{
        "AreaId": "450000",
        "label": "广西壮族自治区",
        "PatentId": "0",
        "Level": 1,
        "value": "450000",
        "children": [{
            "AreaId": "450100",
            "label": "南宁市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450100",
            "children": [{
                "AreaId": "450102",
                "label": "兴宁区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450102",
                "isLeaf": true
            }, {
                "AreaId": "450103",
                "label": "青秀区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450103",
                "isLeaf": true
            }, {
                "AreaId": "450105",
                "label": "江南区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450105",
                "isLeaf": true
            }, {
                "AreaId": "450107",
                "label": "西乡塘区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450107",
                "isLeaf": true
            }, {
                "AreaId": "450108",
                "label": "良庆区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450108",
                "isLeaf": true
            }, {
                "AreaId": "450109",
                "label": "邕宁区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450109",
                "isLeaf": true
            }, {
                "AreaId": "450114",
                "label": "南宁市东盟经济技术开发区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450114",
                "isLeaf": true
            }, {
                "AreaId": "450122",
                "label": "武鸣区",
                "PatentId": "450100",
                "Level": 3,
                "value": "450122",
                "isLeaf": true
            }, {
                "AreaId": "450123",
                "label": "隆安县",
                "PatentId": "450100",
                "Level": 3,
                "value": "450123",
                "isLeaf": true
            }, {
                "AreaId": "450124",
                "label": "马山县",
                "PatentId": "450100",
                "Level": 3,
                "value": "450124",
                "isLeaf": true
            }, {
                "AreaId": "450125",
                "label": "上林县",
                "PatentId": "450100",
                "Level": 3,
                "value": "450125",
                "isLeaf": true
            }, {
                "AreaId": "450126",
                "label": "宾阳县",
                "PatentId": "450100",
                "Level": 3,
                "value": "450126",
                "isLeaf": true
            }, {
                "AreaId": "450127",
                "label": "横县",
                "PatentId": "450100",
                "Level": 3,
                "value": "450127",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450200",
            "label": "柳州市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450200",
            "children": [{
                "AreaId": "450202",
                "label": "城中区",
                "PatentId": "450200",
                "Level": 3,
                "value": "450202",
                "isLeaf": true
            }, {
                "AreaId": "450203",
                "label": "鱼峰区",
                "PatentId": "450200",
                "Level": 3,
                "value": "450203",
                "isLeaf": true
            }, {
                "AreaId": "450204",
                "label": "柳南区",
                "PatentId": "450200",
                "Level": 3,
                "value": "450204",
                "isLeaf": true
            }, {
                "AreaId": "450205",
                "label": "柳北区",
                "PatentId": "450200",
                "Level": 3,
                "value": "450205",
                "isLeaf": true
            }, {
                "AreaId": "450221",
                "label": "柳江区",
                "PatentId": "450200",
                "Level": 3,
                "value": "450221",
                "isLeaf": true
            }, {
                "AreaId": "450222",
                "label": "柳城县",
                "PatentId": "450200",
                "Level": 3,
                "value": "450222",
                "isLeaf": true
            }, {
                "AreaId": "450223",
                "label": "鹿寨县",
                "PatentId": "450200",
                "Level": 3,
                "value": "450223",
                "isLeaf": true
            }, {
                "AreaId": "450224",
                "label": "融安县",
                "PatentId": "450200",
                "Level": 3,
                "value": "450224",
                "isLeaf": true
            }, {
                "AreaId": "450225",
                "label": "融水苗族自治县",
                "PatentId": "450200",
                "Level": 3,
                "value": "450225",
                "isLeaf": true
            }, {
                "AreaId": "450226",
                "label": "三江侗族自治县",
                "PatentId": "450200",
                "Level": 3,
                "value": "450226",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450300",
            "label": "桂林市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450300",
            "children": [{
                "AreaId": "450302",
                "label": "秀峰区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450302",
                "isLeaf": true
            }, {
                "AreaId": "450303",
                "label": "叠彩区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450303",
                "isLeaf": true
            }, {
                "AreaId": "450304",
                "label": "象山区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450304",
                "isLeaf": true
            }, {
                "AreaId": "450305",
                "label": "七星区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450305",
                "isLeaf": true
            }, {
                "AreaId": "450311",
                "label": "雁山区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450311",
                "isLeaf": true
            }, {
                "AreaId": "450321",
                "label": "阳朔县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450321",
                "isLeaf": true
            }, {
                "AreaId": "450322",
                "label": "临桂区",
                "PatentId": "450300",
                "Level": 3,
                "value": "450322",
                "isLeaf": true
            }, {
                "AreaId": "450323",
                "label": "灵川县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450323",
                "isLeaf": true
            }, {
                "AreaId": "450324",
                "label": "全州县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450324",
                "isLeaf": true
            }, {
                "AreaId": "450325",
                "label": "兴安县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450325",
                "isLeaf": true
            }, {
                "AreaId": "450326",
                "label": "永福县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450326",
                "isLeaf": true
            }, {
                "AreaId": "450327",
                "label": "灌阳县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450327",
                "isLeaf": true
            }, {
                "AreaId": "450328",
                "label": "龙胜各族自治县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450328",
                "isLeaf": true
            }, {
                "AreaId": "450329",
                "label": "资源县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450329",
                "isLeaf": true
            }, {
                "AreaId": "450330",
                "label": "平乐县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450330",
                "isLeaf": true
            }, {
                "AreaId": "450331",
                "label": "荔蒲县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450331",
                "isLeaf": true
            }, {
                "AreaId": "450332",
                "label": "恭城瑶族自治县",
                "PatentId": "450300",
                "Level": 3,
                "value": "450332",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450400",
            "label": "梧州市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450400",
            "children": [{
                "AreaId": "450403",
                "label": "万秀区",
                "PatentId": "450400",
                "Level": 3,
                "value": "450403",
                "isLeaf": true
            }, {
                "AreaId": "450404",
                "label": "蝶山区",
                "PatentId": "450400",
                "Level": 3,
                "value": "450404",
                "isLeaf": true
            }, {
                "AreaId": "450405",
                "label": "长洲区",
                "PatentId": "450400",
                "Level": 3,
                "value": "450405",
                "isLeaf": true
            }, {
                "AreaId": "450421",
                "label": "苍梧县",
                "PatentId": "450400",
                "Level": 3,
                "value": "450421",
                "isLeaf": true
            }, {
                "AreaId": "450422",
                "label": "藤县",
                "PatentId": "450400",
                "Level": 3,
                "value": "450422",
                "isLeaf": true
            }, {
                "AreaId": "450423",
                "label": "蒙山县",
                "PatentId": "450400",
                "Level": 3,
                "value": "450423",
                "isLeaf": true
            }, {
                "AreaId": "450481",
                "label": "岑溪市",
                "PatentId": "450400",
                "Level": 3,
                "value": "450481",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450500",
            "label": "北海市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450500",
            "children": [{
                "AreaId": "450502",
                "label": "海城区",
                "PatentId": "450500",
                "Level": 3,
                "value": "450502",
                "isLeaf": true
            }, {
                "AreaId": "450503",
                "label": "银海区",
                "PatentId": "450500",
                "Level": 3,
                "value": "450503",
                "isLeaf": true
            }, {
                "AreaId": "450512",
                "label": "铁山港区",
                "PatentId": "450500",
                "Level": 3,
                "value": "450512",
                "isLeaf": true
            }, {
                "AreaId": "450521",
                "label": "合浦县",
                "PatentId": "450500",
                "Level": 3,
                "value": "450521",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450600",
            "label": "防城港市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450600",
            "children": [{
                "AreaId": "450602",
                "label": "港口区",
                "PatentId": "450600",
                "Level": 3,
                "value": "450602",
                "isLeaf": true
            }, {
                "AreaId": "450603",
                "label": "防城区",
                "PatentId": "450600",
                "Level": 3,
                "value": "450603",
                "isLeaf": true
            }, {
                "AreaId": "450621",
                "label": "上思县",
                "PatentId": "450600",
                "Level": 3,
                "value": "450621",
                "isLeaf": true
            }, {
                "AreaId": "450681",
                "label": "东兴市",
                "PatentId": "450600",
                "Level": 3,
                "value": "450681",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450700",
            "label": "钦州市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450700",
            "children": [{
                "AreaId": "450701",
                "label": "钦州港区",
                "PatentId": "450700",
                "Level": 3,
                "value": "450701",
                "isLeaf": true
            }, {
                "AreaId": "450702",
                "label": "钦南区",
                "PatentId": "450700",
                "Level": 3,
                "value": "450702",
                "isLeaf": true
            }, {
                "AreaId": "450703",
                "label": "钦北区",
                "PatentId": "450700",
                "Level": 3,
                "value": "450703",
                "isLeaf": true
            }, {
                "AreaId": "450705",
                "label": "中马产业园区",
                "PatentId": "450700",
                "Level": 3,
                "value": "450705",
                "isLeaf": true
            }, {
                "AreaId": "450721",
                "label": "灵山县",
                "PatentId": "450700",
                "Level": 3,
                "value": "450721",
                "isLeaf": true
            }, {
                "AreaId": "450722",
                "label": "浦北县",
                "PatentId": "450700",
                "Level": 3,
                "value": "450722",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450800",
            "label": "贵港市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450800",
            "children": [{
                "AreaId": "450802",
                "label": "港北区",
                "PatentId": "450800",
                "Level": 3,
                "value": "450802",
                "isLeaf": true
            }, {
                "AreaId": "450803",
                "label": "港南区",
                "PatentId": "450800",
                "Level": 3,
                "value": "450803",
                "isLeaf": true
            }, {
                "AreaId": "450804",
                "label": "覃塘区",
                "PatentId": "450800",
                "Level": 3,
                "value": "450804",
                "isLeaf": true
            }, {
                "AreaId": "450821",
                "label": "平南县",
                "PatentId": "450800",
                "Level": 3,
                "value": "450821",
                "isLeaf": true
            }, {
                "AreaId": "450881",
                "label": "桂平市",
                "PatentId": "450800",
                "Level": 3,
                "value": "450881",
                "isLeaf": true
            }]
        }, {
            "AreaId": "450900",
            "label": "玉林市",
            "PatentId": "450000",
            "Level": 2,
            "value": "450900",
            "children": [{
                "AreaId": "450902",
                "label": "玉州区",
                "PatentId": "450900",
                "Level": 3,
                "value": "450902",
                "isLeaf": true
            }, {
                "AreaId": "450921",
                "label": "容县",
                "PatentId": "450900",
                "Level": 3,
                "value": "450921",
                "isLeaf": true
            }, {
                "AreaId": "450922",
                "label": "陆川县",
                "PatentId": "450900",
                "Level": 3,
                "value": "450922",
                "isLeaf": true
            }, {
                "AreaId": "450923",
                "label": "博白县",
                "PatentId": "450900",
                "Level": 3,
                "value": "450923",
                "isLeaf": true
            }, {
                "AreaId": "450924",
                "label": "兴业县",
                "PatentId": "450900",
                "Level": 3,
                "value": "450924",
                "isLeaf": true
            }, {
                "AreaId": "450981",
                "label": "北流市",
                "PatentId": "450900",
                "Level": 3,
                "value": "450981",
                "isLeaf": true
            }]
        }, {
            "AreaId": "451000",
            "label": "百色市",
            "PatentId": "450000",
            "Level": 2,
            "value": "451000",
            "children": [{
                "AreaId": "451002",
                "label": "右江区",
                "PatentId": "451000",
                "Level": 3,
                "value": "451002",
                "isLeaf": true
            }, {
                "AreaId": "451021",
                "label": "田阳县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451021",
                "isLeaf": true
            }, {
                "AreaId": "451022",
                "label": "田东县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451022",
                "isLeaf": true
            }, {
                "AreaId": "451023",
                "label": "平果县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451023",
                "isLeaf": true
            }, {
                "AreaId": "451024",
                "label": "德保县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451024",
                "isLeaf": true
            }, {
                "AreaId": "451025",
                "label": "靖西市",
                "PatentId": "451000",
                "Level": 3,
                "value": "451025",
                "isLeaf": true
            }, {
                "AreaId": "451026",
                "label": "那坡县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451026",
                "isLeaf": true
            }, {
                "AreaId": "451027",
                "label": "凌云县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451027",
                "isLeaf": true
            }, {
                "AreaId": "451028",
                "label": "乐业县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451028",
                "isLeaf": true
            }, {
                "AreaId": "451029",
                "label": "田林县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451029",
                "isLeaf": true
            }, {
                "AreaId": "451030",
                "label": "西林县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451030",
                "isLeaf": true
            }, {
                "AreaId": "451031",
                "label": "隆林各族自治县",
                "PatentId": "451000",
                "Level": 3,
                "value": "451031",
                "isLeaf": true
            }]
        }, {
            "AreaId": "451100",
            "label": "贺州市",
            "PatentId": "450000",
            "Level": 2,
            "value": "451100",
            "children": [{
                "AreaId": "451102",
                "label": "八步区",
                "PatentId": "451100",
                "Level": 3,
                "value": "451102",
                "isLeaf": true
            }, {
                "AreaId": "451103",
                "label": "平桂区",
                "PatentId": "451100",
                "Level": 3,
                "value": "451103",
                "isLeaf": true
            }, {
                "AreaId": "451121",
                "label": "昭平县",
                "PatentId": "451100",
                "Level": 3,
                "value": "451121",
                "isLeaf": true
            }, {
                "AreaId": "451122",
                "label": "钟山县",
                "PatentId": "451100",
                "Level": 3,
                "value": "451122",
                "isLeaf": true
            }, {
                "AreaId": "451123",
                "label": "富川瑶族自治县",
                "PatentId": "451100",
                "Level": 3,
                "value": "451123",
                "isLeaf": true
            }]
        }, {
            "AreaId": "451200",
            "label": "河池市",
            "PatentId": "450000",
            "Level": 2,
            "value": "451200",
            "children": [{
                "AreaId": "451202",
                "label": "金城江区",
                "PatentId": "451200",
                "Level": 3,
                "value": "451202",
                "isLeaf": true
            }, {
                "AreaId": "451203",
                "label": "宜州新区",
                "PatentId": "451200",
                "Level": 3,
                "value": "451203",
                "isLeaf": true
            }, {
                "AreaId": "451221",
                "label": "南丹县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451221",
                "isLeaf": true
            }, {
                "AreaId": "451222",
                "label": "天峨县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451222",
                "isLeaf": true
            }, {
                "AreaId": "451223",
                "label": "凤山县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451223",
                "isLeaf": true
            }, {
                "AreaId": "451224",
                "label": "东兰县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451224",
                "isLeaf": true
            }, {
                "AreaId": "451225",
                "label": "罗城仫佬族自治县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451225",
                "isLeaf": true
            }, {
                "AreaId": "451226",
                "label": "环江毛南族自治县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451226",
                "isLeaf": true
            }, {
                "AreaId": "451227",
                "label": "巴马瑶族自治县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451227",
                "isLeaf": true
            }, {
                "AreaId": "451228",
                "label": "都安瑶族自治县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451228",
                "isLeaf": true
            }, {
                "AreaId": "451229",
                "label": "大化瑶族自治县",
                "PatentId": "451200",
                "Level": 3,
                "value": "451229",
                "isLeaf": true
            }, {
                "AreaId": "451281",
                "label": "宜州市",
                "PatentId": "451200",
                "Level": 3,
                "value": "451281",
                "isLeaf": true
            }]
        }, {
            "AreaId": "451300",
            "label": "来宾市",
            "PatentId": "450000",
            "Level": 2,
            "value": "451300",
            "children": [{
                "AreaId": "451302",
                "label": "兴宾区",
                "PatentId": "451300",
                "Level": 3,
                "value": "451302",
                "isLeaf": true
            }, {
                "AreaId": "451321",
                "label": "忻城县",
                "PatentId": "451300",
                "Level": 3,
                "value": "451321",
                "isLeaf": true
            }, {
                "AreaId": "451322",
                "label": "象州县",
                "PatentId": "451300",
                "Level": 3,
                "value": "451322",
                "isLeaf": true
            }, {
                "AreaId": "451323",
                "label": "武宣县",
                "PatentId": "451300",
                "Level": 3,
                "value": "451323",
                "isLeaf": true
            }, {
                "AreaId": "451324",
                "label": "金秀瑶族自治县",
                "PatentId": "451300",
                "Level": 3,
                "value": "451324",
                "isLeaf": true
            }, {
                "AreaId": "451381",
                "label": "合山市",
                "PatentId": "451300",
                "Level": 3,
                "value": "451381",
                "isLeaf": true
            }]
        }, {
            "AreaId": "451400",
            "label": "崇左市",
            "PatentId": "450000",
            "Level": 2,
            "value": "451400",
            "children": [{
                "AreaId": "451402",
                "label": "江洲区",
                "PatentId": "451400",
                "Level": 3,
                "value": "451402",
                "isLeaf": true
            }, {
                "AreaId": "451403",
                "label": "城市工业区",
                "PatentId": "451400",
                "Level": 3,
                "value": "451403",
                "isLeaf": true
            }, {
                "AreaId": "451421",
                "label": "扶绥县",
                "PatentId": "451400",
                "Level": 3,
                "value": "451421",
                "isLeaf": true
            }, {
                "AreaId": "451422",
                "label": "宁明县",
                "PatentId": "451400",
                "Level": 3,
                "value": "451422",
                "isLeaf": true
            }, {
                "AreaId": "451423",
                "label": "龙州县",
                "PatentId": "451400",
                "Level": 3,
                "value": "451423",
                "isLeaf": true
            }, {
                "AreaId": "451424",
                "label": "大新县",
                "PatentId": "451400",
                "Level": 3,
                "value": "451424",
                "isLeaf": true
            }, {
                "AreaId": "451425",
                "label": "天等县",
                "PatentId": "451400",
                "Level": 3,
                "value": "451425",
                "isLeaf": true
            }, {
                "AreaId": "451481",
                "label": "凭祥市",
                "PatentId": "451400",
                "Level": 3,
                "value": "451481",
                "isLeaf": true
            }]
        }]
    }];
}